dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: rabbitmq
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 2.2.0
- name: store
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
- name: workshop-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: workshop-demo2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
